inherit_gem:
  rubocop-lts: config/rubygem_rspec.yml

inherit_from:
  - .rubocop_rspec.yml

plugins: rubocop-on-rbs

RBS:
  Enabled: true

AllCops:
  DisplayCopNames: true # Display the name of the failing cops
  Exclude:
    - 'gemfiles/vendor/**/*'
    - 'vendor/**/*'
    - '**/.irbrc'

Layout/IndentationConsistency:
  Exclude: ['*.md']

Metrics/BlockLength:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/BlockNesting:
  Max: 2

Layout/LineLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 4

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/UnusedBlockArgument:
  Exclude:
    - 'spec/**/*.rb'
    - 'gemfiles/vendor/**/*'
    - 'vendor/**/*'
    - '**/.irbrc'

# Test if we can turn this back on after upgrading rubocop-md.
# It is still an open issue, so not expecting it to be fixed.
# See: https://github.com/rubocop/rubocop-md/issues/28
Layout/InitialIndentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    map:      'collect'
    reduce:   'inject'
    find:     'detect'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Encoding:
  Enabled: false

# Does not work with older rubies
#Style/MapToHash:
#  Enabled: false

# Does not work with older rubies
#Style/RedundantBegin:
#  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Gemspec/DependencyVersion:
  Enabled: false

Lint/LiteralInInterpolation:
  Exclude:
    - 'spec/**/*.rb'
