services:
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.3.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config-ssl.json:/app/config.json:Z
    environment:
      LOG_LEVEL: "debug"
      SERVER_PORT: 8080
      JSON_CONFIG_PATH: /app/config.json
